# BOCRacePlugin Configuration
# Race timeout in seconds
race-timeout: 60

# Maximum players per multiplayer race
max-players: 10

# Sound settings
sounds:
  start-ding: true
  finish-fireworks: true

# Color settings
colors:
  prefix: GOLD
  broadcast: AQUA

# Debug modes
debug: false
debug-race: false    # Specific debug for race mechanics (button clicks, line detection, etc.)
debug-setup: false  # Specific debug for course setup commands

# Configuration version (for future updates)
config-version: 1
