name: BOCRacePlugin
version: 1.0.0
main: com.bocrace.BOCRacePlugin
api-version: 1.21
description: A boat racing plugin for Minecraft Paper
author: AbnVet
website: https://github.com/AbnVet/MCRacePlugin

depend: [PlaceholderAPI]
softdepend: []

commands:
  bocrace:
    description: Main command for BOCRacePlugin
    usage: /bocrace help
    aliases: [brp]
    permission: bocrace.use

permissions:
  bocrace.use:
    description: Allows use of BOCRacePlugin commands
    default: true
